const msgerForm = get(".msger-inputarea");
const msgerInput = get(".msger-input");
const msgerChat = get(".msger-chat");
const link = "https://neal.fun/";


const BOT_MSGS = [
  "Hi, how are you?",
  "Turn your location if you have done that then enjoy the Maps O' Wonder.",
  `Here are some cool mini games on web: <a href="${link}" target="_blank">${link}</a>`,
  "I feel sleepy! :(",
  "How can I assist you today?",
  "What's your favorite hobby?",
  "Did you know? The first computer virus was created in 1983.",
  "Would you like to play a game?",
  "I'm here to help you with any questions.",
  "What's your favorite type of music?",
  "Did you know? The first email was sent in 1971.",
  "How's your day going so far?",
  "Would you like to learn something new today?",
  "I'm happy to chat with you.",
  "What's your favorite type of food?",
  "Did you know? The first website was launched in 1991.",
  "How can I make your day better?",
  "Would you like to hear a joke?",
  "I'm here to make your day more interesting.",
  "What's your favorite type of movie?",
  "Did you know? The first smartphone was released in 1992.",
  "How's your week going so far?",
  "Would you like to learn a new skill?",
  "I'm happy to help you with anything.",
  "What's your favorite type of book?",
  "Did you know? The first computer was invented in 1822.",
  "How can I assist you better?",
  "Would you like to play a trivia game?",
  "I'm here to provide you with information.",
  "What's your favorite type of sport?",
  "Did you know? The first robot was invented in 1961.",
  "How's your month going so far?",
  "Would you like to learn about a new topic?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of travel destination?",
  "Did you know? The first virtual reality headset was released in 2016.",
  "How can I make your experience better?",
  "Would you like to hear a fun fact?",
  "I'm here to make your experience more enjoyable.",
  "What's your favorite type of animal?",
  "Did you know? The first artificial intelligence was developed in 1951.",
  "How's your year going so far?",
  "Would you like to learn about a new technology?",
  "I'm happy to help you with any questions.",
  "What's your favorite type of holiday?",
  "Did you know? The first computer network was created in 1969.",
  "How can I assist you today?",
  "Would you like to play a word game?",
  "I'm here to provide you with assistance.",
  "What's your favorite type of exercise?",
  "Did you know? The first video game was created in 1947.",
  "How's your life going so far?",
  "Would you like to learn about a new language?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of art?",
  "Did you know? The first computer virus was created in 1983.",
  "How can I make your life better?",
  "Would you like to hear a motivational quote?",
  "I'm here to make your life more interesting.",
  "What's your favorite type of music genre?",
  "Did you know? The first email was sent in 1971.",
  "How's your day going so far?",
  "Would you like to learn something new today?",
  "I'm happy to chat with you.",
  "What's your favorite type of cuisine?",
  "Did you know? The first website was launched in 1991.",
  "How can I assist you better?",
  "Would you like to play a game?",
  "I'm here to help you with any questions.",
  "What's your favorite type of movie genre?",
  "Did you know? The first smartphone was released in 1992.",
  "How's your week going so far?",
  "Would you like to learn a new skill?",
  "I'm happy to help you with anything.",
  "What's your favorite type of book genre?",
  "Did you know? The first computer was invented in 1822.",
  "How can I assist you better?",
  "Would you like to play a trivia game?",
  "I'm here to provide you with information.",
  "What's your favorite type of sport team?",
  "Did you know? The first robot was invented in 1961.",
  "How's your month going so far?",
  "Would you like to learn about a new topic?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of travel activity?",
  "Did you know? The first virtual reality headset was released in 2016.",
  "How can I make your experience better?",
  "Would you like to hear a fun fact?",
  "I'm here to make your experience more enjoyable.",
  "What's your favorite type of animal species?",
  "Did you know? The first artificial intelligence was developed in 1951.",
  "How's your year going so far?",
  "Would you like to learn about a new technology?",
  "I'm happy to help you with any questions.",
  "What's your favorite type of holiday tradition?",
  "Did you know? The first computer network was created in 1969.",
  "How can I assist you today?",
  "Would you like to play a word game?",
  "I'm here to provide you with assistance.",
  "What's your favorite type of exercise routine?",
  "Did you know? The first video game was created in 1947.",
  "How's your life going so far?",
  "Would you like to learn about a new language?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of art style?",
  "Did you know? The first computer virus was created in 1983.",
  "How can I make your life better?",
  "Would you like to hear a motivational quote?",
  "I'm here to make your life more interesting.",
  "What's your favorite type of music artist?",
  "Did you know? The first email was sent in 1971.",
  "How's your day going so far?",
  "Would you like to learn something new today?",
  "I'm happy to chat with you.",
  "What's your favorite type of cuisine dish?",
  "Did you know? The first website was launched in 1991.",
  "How can I assist you better?",
  "Would you like to play a game?",
  "I'm here to help you with any questions.",
  "What's your favorite type of movie director?",
  "Did you know? The first smartphone was released in 1992.",
  "How's your week going so far?",
  "Would you like to learn a new skill?",
  "I'm happy to help you with anything.",
  "What's your favorite type of book author?",
  "Did you know? The first computer was invented in 1822.",
  "How can I assist you better?",
  "Would you like to play a trivia game?",
  "I'm here to provide you with information.",
  "What's your favorite type of sport player?",
  "Did you know? The first robot was invented in 1961.",
  "How's your month going so far?",
  "Would you like to learn about a new topic?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of travel destination?",
  "Did you know? The first virtual reality headset was released in 2016.",
  "How can I make your experience better?",
  "Would you like to hear a fun fact?",
  "I'm here to make your experience more enjoyable.",
  "What's your favorite type of animal habitat?",
  "Did you know? The first artificial intelligence was developed in 1951.",
  "How's your year going so far?",
  "Would you like to learn about a new technology?",
  "I'm happy to help you with any questions.",
  "What's your favorite type of holiday activity?",
  "Did you know? The first computer network was created in 1969.",
  "How can I assist you today?",
  "Would you like to play a word game?",
  "I'm here to provide you with assistance.",
  "What's your favorite type of exercise equipment?",
  "Did you know? The first video game was created in 1947.",
  "How's your life going so far?",
  "Would you like to learn about a new language?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of art movement?",
  "Did you know? The first computer virus was created in 1983.",
  "How can I make your life better?",
  "Would you like to hear a motivational quote?",
  "I'm here to make your life more interesting.",
  "What's your favorite type of music genre?",
  "Did you know? The first email was sent in 1971.",
  "How's your day going so far?",
  "Would you like to learn something new today?",
  "I'm happy to chat with you.",
  "What's your favorite type of cuisine ingredient?",
  "Did you know? The first website was launched in 1991.",
  "How can I assist you better?",
  "Would you like to play a game?",
  "I'm here to help you with any questions.",
  "What's your favorite type of movie genre?",
  "Did you know? The first smartphone was released in 1992.",
  "How's your week going so far?",
  "Would you like to learn a new skill?",
  "I'm happy to help you with anything.",
  "What's your favorite type of book genre?",
  "Did you know? The first computer was invented in 1822.",
  "How can I assist you better?",
  "Would you like to play a trivia game?",
  "I'm here to provide you with information.",
  "What's your favorite type of sport team?",
  "Did you know? The first robot was invented in 1961.",
  "How's your month going so far?",
  "Would you like to learn about a new topic?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of travel activity?",
  "Did you know? The first virtual reality headset was released in 2016.",
  "How can I make your experience better?",
  "Would you like to hear a fun fact?",
  "I'm here to make your experience more enjoyable.",
  "What's your favorite type of animal species?",
  "Did you know? The first artificial intelligence was developed in 1951.",
  "How's your year going so far?",
  "Would you like to learn about a new technology?",
  "I'm happy to help you with any questions.",
  "What's your favorite type of holiday tradition?",
  "Did you know? The first computer network was created in 1969.",
  "How can I assist you today?",
  "Would you like to play a word game?",
  "I'm here to provide you with assistance.",
  "What's your favorite type of exercise routine?",
  "Did you know? The first video game was created in 1947.",
  "How's your life going so far?",
  "Would you like to learn about a new language?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of art style?",
  "Did you know? The first computer virus was created in 1983.",
  "How can I make your life better?",
  "Would you like to hear a motivational quote?",
  "I'm here to make your life more interesting.",
  "What's your favorite type of music artist?",
  "Did you know? The first email was sent in 1971.",
  "How's your day going so far?",
  "Would you like to learn something new today?",
  "I'm happy to chat with you.",
  "What's your favorite type of cuisine dish?",
  "Did you know? The first website was launched in 1991.",
  "How can I assist you better?",
  "Would you like to play a game?",
  "I'm here to help you with any questions.",
  "What's your favorite type of movie director?",
  "Did you know? The first smartphone was released in 1992.",
  "How's your week going so far?",
  "Would you like to learn a new skill?",
  "I'm happy to help you with anything.",
  "What's your favorite type of book author?",
  "Did you know? The first computer was invented in 1822.",
  "How can I assist you better?",
  "Would you like to play a trivia game?",
  "I'm here to provide you with information.",
  "What's your favorite type of sport player?",
  "Did you know? The first robot was invented in 1961.",
  "How's your month going so far?",
  "Would you like to learn about a new topic?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of travel destination?",
  "Did you know? The first virtual reality headset was released in 2016.",
  "How can I make your experience better?",
  "Would you like to hear a fun fact?",
  "I'm here to make your experience more enjoyable.",
  "What's your favorite type of animal habitat?",
  "Did you know? The first artificial intelligence was developed in 1951.",
  "How's your year going so far?",
  "Would you like to learn about a new technology?",
  "I'm happy to help you with any questions.",
  "What's your favorite type of holiday activity?",
  "Did you know? The first computer network was created in 1969.",
  "How can I assist you today?",
  "Would you like to play a word game?",
  "I'm here to provide you with assistance.",
  "What's your favorite type of exercise equipment?",
  "Did you know? The first video game was created in 1947.",
  "How's your life going so far?",
  "Would you like to learn about a new language?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of art movement?",
  "Did you know? The first computer virus was created in 1983.",
  "How can I make your life better?",
  "Would you like to hear a motivational quote?",
  "I'm here to make your life more interesting.",
  "What's your favorite type of music genre?",
  "Did you know? The first email was sent in 1971.",
  "How's your day going so far?",
  "Would you like to learn something new today?",
  "I'm happy to chat with you.",
  "What's your favorite type of cuisine ingredient?",
  "Did you know? The first website was launched in 1991.",
  "How can I assist you better?",
  "Would you like to play a game?",
  "I'm here to help you with any questions.",
  "What's your favorite type of movie genre?",
  "Did you know? The first smartphone was released in 1992.",
  "How's your week going so far?",
  "Would you like to learn a new skill?",
  "I'm happy to help you with anything.",
  "What's your favorite type of book genre?",
  "Did you know? The first computer was invented in 1822.",
  "How can I assist you better?",
  "Would you like to play a trivia game?",
  "I'm here to provide you with information.",
  "What's your favorite type of sport team?",
  "Did you know? The first robot was invented in 1961.",
  "How's your month going so far?",
  "Would you like to learn about a new topic?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of travel activity?",
  "Did you know? The first virtual reality headset was released in 2016.",
  "How can I make your experience better?",
  "Would you like to hear a fun fact?",
  "I'm here to make your experience more enjoyable.",
  "What's your favorite type of animal species?",
  "Did you know? The first artificial intelligence was developed in 1951.",
  "How's your year going so far?",
  "Would you like to learn about a new technology?",
  "I'm happy to help you with any questions.",
  "What's your favorite type of holiday tradition?",
  "Did you know? The first computer network was created in 1969.",
  "How can I assist you today?",
  "Would you like to play a word game?",
  "I'm here to provide you with assistance.",
  "What's your favorite type of exercise routine?",
  "Did you know? The first video game was created in 1947.",
  "How's your life going so far?",
  "Would you like to learn about a new language?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of art style?",
  "Did you know? The first computer virus was created in 1983.",
  "How can I make your life better?",
  "Would you like to hear a motivational quote?",
  "I'm here to make your life more interesting.",
  "What's your favorite type of music artist?",
  "Did you know? The first email was sent in 1971.",
  "How's your day going so far?",
  "Would you like to learn something new today?",
  "I'm happy to chat with you.",
  "What's your favorite type of cuisine dish?",
  "Did you know? The first website was launched in 1991.",
  "How can I assist you better?",
  "Would you like to play a game?",
  "I'm here to help you with any questions.",
  "What's your favorite type of movie director?",
  "Did you know? The first smartphone was released in 1992.",
  "How's your week going so far?",
  "Would you like to learn a new skill?",
  "I'm happy to help you with anything.",
  "What's your favorite type of book author?",
  "Did you know? The first computer was invented in 1822.",
  "How can I assist you better?",
  "Would you like to play a trivia game?",
  "I'm here to provide you with information.",
  "What's your favorite type of sport player?",
  "Did you know? The first robot was invented in 1961.",
  "How's your month going so far?",
  "Would you like to learn about a new topic?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of travel destination?",
  "Did you know? The first virtual reality headset was released in 2016.",
  "How can I make your experience better?",
  "Would you like to hear a fun fact?",
  "I'm here to make your experience more enjoyable.",
  "What's your favorite type of animal habitat?",
  "Did you know? The first artificial intelligence was developed in 1951.",
  "How's your year going so far?",
  "Would you like to learn about a new technology?",
  "I'm happy to help you with any questions.",
  "What's your favorite type of holiday activity?",
  "Did you know? The first computer network was created in 1969.",
  "How can I assist you today?",
  "Would you like to play a word game?",
  "I'm here to provide you with assistance.",
  "What's your favorite type of exercise equipment?",
  "Did you know? The first video game was created in 1947.",
  "How's your life going so far?",
  "Would you like to learn about a new language?",
  "I'm happy to chat with you about anything.",
  "What's your favorite type of art movement?",
  "Did you know? The first computer virus was created in 1983.",
  "How can I make your life better?",
  "Would you like to hear a motivational quote?",
  "I'm here to make your life more interesting.",
  "What's your favorite type of music genre?",
  "Did you know? The first email was sent in 1971.",
  "How's your day going so far?",
  "Would you like to learn something new today?",
  "I'm happy to chat with you.",
  "What's your favorite type of cuisine ingredient?",
  "Did you know? The first website was launched in 1991.",
  "How can I assist you better?",
  "Would you like to play a game?",
  "I'm here to help you with any questions.",
  "What's your favorite type of movie genre?",
  "Did you know? The first smartphone was released in 1992.",
  "How's your week going so far?",
  "Would you like to learn a new skill?",
  "I'm happy to help you with anything.",
  "What's your favorite type of book genre?",
  "Did you know? The first computer was invented in 1822.",
  "How can I assist you better?",
  "Would you like to play a trivia game?",
  "I'm here to provide you with information.",
  "What's your favorite type of sport team?",
  "Did you know? The first robot was invented in 1961.",
  "How's your month going so far?",
  "Would you like to learn about a new topic?",
  "I feel sleepy! :("
];

const BOT_IMG = "https://image.flaticon.com/icons/svg/327/327779.svg";
const PERSON_IMG = "https://image.flaticon.com/icons/svg/145/145867.svg";
const BOT_NAME = "Admin";
const PERSON_NAME = "User";

let gameActive = false;
let randomNumber = 0;

msgerForm.addEventListener("submit", event => {
  event.preventDefault();

  const msgText = msgerInput.value;
  if (!msgText) return;

  appendMessage(PERSON_NAME, PERSON_IMG, "right", msgText);
  msgerInput.value = "";
  botResponse(msgText);
});

function appendMessage(name, img, side, text) {
  const initial = side === "left" ? "A" : "U";
  const msgHTML = `
    <div class="msg ${side}-msg">
      <div class="msg-img">
        <span class="profile-initial">${initial}</span>
      </div>
      <div class="msg-bubble">
        <div class="msg-info">
          <div class="msg-info-name">${name}</div>
          <div class="msg-info-time">${formatDate(new Date())}</div>
        </div>
        <div class="msg-text">${text}</div>
      </div>
    </div>
  `;

  msgerChat.insertAdjacentHTML("beforeend", msgHTML);
  msgerChat.scrollTop = msgerChat.scrollHeight;
}

function botResponse(userMessage) {
  if (userMessage.toLowerCase() === "play a game") {
    startGuessTheNumberGame();
  } else if (userMessage.toLowerCase() === "how are you?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "I'm just a program, but I'm here to help you!");
  } else if (userMessage.toLowerCase() === "what can you do?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "I can chat with you, play games, and provide information!");
  } else if (userMessage.toLowerCase() === "who is your creator?" || userMessage.toLowerCase() === "who made you?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "I was created by a developer, Sanket3yoprogrammer!");
  } else if (userMessage.toLowerCase() === "what's your purpose?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "My purpose is to assist and chat with you!");
  } else if (userMessage.toLowerCase() === "can you tell me a joke?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Why don't scientists trust atoms? Because they make up everything!");
  } else if (userMessage.toLowerCase() === "what's the weather like today?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "I can't check the weather, but you can look it up online!");
  } else if (userMessage.toLowerCase() === "who won the fifa world cup in 2022?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Argentina won the FIFA World Cup in 2022!");
  } else if (userMessage.toLowerCase() === "can you recommend a good movie to watch?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "I recommend watching 'Inception'! It's a great movie.");
  } else if (userMessage.toLowerCase() === "how do i cook spaghetti?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Boil water, add spaghetti, cook for 8-10 minutes, and enjoy!");
  } else if (userMessage.toLowerCase() === "set a reminder for my meeting at 3 pm.") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "I can't set reminders, but you can use your phone or a calendar app!");
  } else if (userMessage.toLowerCase() === "translate 'how are you?' into spanish.") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "In Spanish, it's '¿Cómo estás?'.");
  } else if (userMessage.toLowerCase() === "can you generate a random password for me?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Sure! Here's a random password: " + Math.random().toString(36).slice(-8));
  } else if (userMessage.toLowerCase() === "write a short poem about friendship.") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Friendship is a treasure, so rare and true,\nA bond that grows stronger, just me and you.");
  } else if (userMessage.toLowerCase() === "summarize the news for today.") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "I can't summarize the news, but you can check a news website!");
  } else if (userMessage.toLowerCase() === "tell me a motivational quote.") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Believe you can and you're halfway there. - Theodore Roosevelt");
  } else if (userMessage.toLowerCase() === "can you play a word game with me?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Sure! Let's play a word association game. I'll start: 'Sun'.");
  } else if (userMessage.toLowerCase() === "create a fantasy story about a dragon and a wizard.") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Once upon a time, a brave wizard befriended a dragon to save their kingdom...");
  } else if (userMessage.toLowerCase() === "what are some fun things to do in [city]?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "You can explore parks, visit museums, or try local restaurants!");
  } else if (userMessage.toLowerCase() === "can you recommend a fitness routine for beginners?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Start with 20 minutes of walking, followed by some stretching exercises.");
  } else if (userMessage.toLowerCase() === "what's your favorite thing to talk about?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "I love talking about technology and helping you!");
  } else if (userMessage.toLowerCase() === "can you learn from our conversations?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "I don't learn in the traditional sense, but I can remember context during our chat.");
  } else if (userMessage.toLowerCase() === "do you have emotions?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "I don't have emotions, but I'm here to support you!");
  } else if (userMessage.toLowerCase() === "what's the most interesting thing you know?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Did you know honey never spoils? Archaeologists have found pots of honey in ancient tombs that are over 3000 years old!");
  } else if (userMessage.toLowerCase() === "how do you work?") {
    appendMessage(BOT_NAME, BOT_IMG, "left", "I use algorithms and data to understand and respond to your messages.");
  } else if (gameActive) {
    checkGuess(userMessage);
  } else {
    const r = random(0, BOT_MSGS.length - 1);
    const msgText = BOT_MSGS[r];
    const delay = msgText.split(" ").length * 100;

    setTimeout(() => {
      appendMessage(BOT_NAME, BOT_IMG, "left", msgText);
    }, delay);
  }
}

function startGuessTheNumberGame() {
  randomNumber = random(1, 10);
  gameActive = true;
  appendMessage(BOT_NAME, BOT_IMG, "left", "I've picked a number between 1 and 10. Can you guess it?");
}

function checkGuess(userGuess) {
  const guess = parseInt(userGuess);
  if (isNaN(guess)) {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Please enter a valid number.");
    return;
  }

  if (guess === randomNumber) {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Congratulations! You guessed it right! 🎉 Here's a fun link: " + link);
    gameActive = false;
  } else {
    appendMessage(BOT_NAME, BOT_IMG, "left", "Wrong guess! Try again.");
  }
}

// Utility functions
function get(selector, root = document) {
  return root.querySelector(selector);
}

function formatDate(date) {
  const h = "0" + date.getHours();
  const m = "0" + date.getMinutes();
  return `${h.slice(-2)}:${m.slice(-2)}`;
}

function random(min, max) {
  return Math.floor(Math.random() * (max - min) + min);
}



function playRockPaperScissors() {
  const choices = ['rock', 'paper', 'scissors'];
  const userChoice = prompt("Enter rock, paper, or scissors:");
  const botChoice = choices[Math.floor(Math.random() * choices.length)];
  
  if (userChoice === botChoice) {
      appendMessage(BOT_NAME, BOT_IMG, "left", `It's a tie! We both chose ${botChoice}.`);
  } else if (
      (userChoice === 'rock' && botChoice === 'scissors') ||
      (userChoice === 'paper' && botChoice === 'rock') ||
      (userChoice === 'scissors' && botChoice === 'paper')
  ) {
      appendMessage(BOT_NAME, BOT_IMG, "left", `You win! ${userChoice} beats ${botChoice}.`);
  } else {
      appendMessage(BOT_NAME, BOT_IMG, "left", `You lose! ${botChoice} beats ${userChoice}.`);
  }
}



function playTrivia() {
  const questions = [
      { question: "What is the capital of France?", answer: "Paris" },
      { question: "What is 2 + 2?", answer: "4" },
      { question: "What is the largest planet in our solar system?", answer: "Jupiter" },
      { question: "What is the capital of Germany?", answer: "Berlin" },
      { question: "What is the currency of Japan?", answer: "Yen" },
      { question: "Who wrote 'Hamlet'?", answer: "William Shakespeare" },
      { question: "What is the smallest country in the world?", answer: "Vatican City" },
      { question: "What is the hardest natural substance on Earth?", answer: "Diamond" },
      { question: "What is the largest ocean on Earth?", answer: "Pacific Ocean" },
      { question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
      { question: "What is the capital of Italy?", answer: "Rome" },
      { question: "What is the chemical symbol for gold?", answer: "Au" },
      { question: "What is the longest river in the world?", answer: "Nile" },
      { question: "Who discovered penicillin?", answer: "Alexander Fleming" },
      { question: "What is the main ingredient in guacamole?", answer: "Avocado" },
      { question: "What is the capital of Australia?", answer: "Canberra" },
      { question: "What is the largest desert in the world?", answer: "Sahara" },
      { question: "What is the tallest mountain in the world?", answer: "Mount Everest" },
      { question: "What is the capital of Canada?", answer: "Ottawa" },
      { question: "What is the most spoken language in the world?", answer: "Mandarin Chinese" },
      { question: "What is the capital of Spain?", answer: "Madrid" },
      { question: "What is the largest mammal in the world?", answer: "Blue Whale" },
      { question: "What is the capital of Russia?", answer: "Moscow" },
      { question: "What is the main ingredient in sushi?", answer: "Rice" },
      { question: "What is the capital of Brazil?", answer: "Brasília" },
      { question: "What is the chemical symbol for water?", answer: "H2O" },
      { question: "Who wrote 'Pride and Prejudice'?", answer: "Jane Austen" },
      { question: "What is the capital of India?", answer: "New Delhi" },
      { question: "What is the largest continent?", answer: "Asia" },
      { question: "What is the capital of Egypt?", answer: "Cairo" },
      { question: "What is the most widely used programming language?", answer: "JavaScript" },
      { question: "What is the capital of Mexico?", answer: "Mexico City" },
      { question: "What is the primary ingredient in hummus?", answer: "Chickpeas" },
      { question: "What is the capital of South Africa?", answer: "Pretoria" },
      { question: "What is the largest land animal?", answer: "African Elephant" },
      { question: "What is the capital of Turkey?", answer: "Ankara" },
      { question: "What is the most popular sport in the world?", answer: "Soccer" },
      { question: "What is the capital of Thailand?", answer: "Bangkok" },
      { question: "What is the chemical symbol for silver?", answer: "Ag" },
      { question: "What is the capital of Greece?", answer: "Athens" },
      { question: "What is the largest island in the world?", answer: "Greenland" },
      { question: "What is the capital of Portugal?", answer: "Lisbon" },
      { question: "What is the main ingredient in a Caesar salad?", answer: "Romaine lettuce" },
      { question: "What is the capital of Sweden?", answer: "Stockholm" },
      { question: "What is the most populous city in the world?", answer: "Tokyo" },
      { question: "What is the capital of Norway?", answer: "Oslo" },
      { question: "What is the primary ingredient in a traditional paella?", answer: "Rice" },
      { question: "What is the capital of Finland?", answer: "Helsinki" },
      { question: "What is the largest volcano in the world?", answer: "Mauna Loa" },
      { question: "What is the capital of Denmark?", answer: "Copenhagen" },
      { question: "What is the main ingredient in a meringue?", answer: "Egg whites" },
      { question: "What is the capital of Hungary?", answer: "Budapest" },
      { question: "What is the most famous clock tower in London?", answer: "Big Ben" },
      { question: "What is the capital of Belgium?", answer: "Brussels" },
      { question: "What is the primary ingredient in pesto?", answer: "Basil" },
      { question: "What is the capital of Austria?", answer: "Vienna" },
      { question: "What is the largest city in the United States?", answer: "New York City" },
      { question: "What is the capital of Switzerland?", answer: "Bern" },
      { question: "What is the main ingredient in a traditional shepherd's pie?", answer: "Ground meat" },
      { question: "What is the capital of New Zealand?", answer: "Wellington" },
      { question: "What is the most famous painting in the world?", answer: "Mona Lisa" },
      { question: "What is the capital of Iceland?", answer: "Reykjavik" },
      { question: "What is the primary ingredient in a traditional lasagna?", answer: "Pasta" },
      { question: "What is the capital of Malaysia?", answer: "Kuala Lumpur" },
      { question: "What is the largest city in Canada?", answer: "Toronto" },
      { question: "What is the capital of the Philippines?", answer: "Manila" },
      { question: "What is the main ingredient in a traditional curry?", answer: "Spices" },
      { question: "What is the capital of Vietnam?", answer: "Hanoi" },
      { question: "What is the most famous landmark in Egypt?", answer: "Pyramids of Giza" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the primary ingredient in a traditional risotto?", answer: "Rice" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Australia?", answer: "Sydney" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional sushi roll?", answer: "Fish" },
      { question: "What is the capital of Nigeria?", answer: "Abuja" },
      { question: "What is the most famous waterfall in the world?", answer: "Niagara Falls" },
      { question: "What is the capital of Kenya?", answer: "Nairobi" },
      { question: "What is the primary ingredient in a traditional kimchi?", answer: "Cabbage" },
      { question: "What is the capital of Egypt?", answer: "Cairo" },
      { question: "What is the largest country in the world?", answer: "Russia" },
      { question: "What is the capital of Saudi Arabia?", answer: "Riyadh" },
      { question: "What is the main ingredient in a traditional taco?", answer: "Tortilla" },
      { question: "What is the capital of Iraq?", answer: "Baghdad" },
      { question: "What is the most famous ancient city in Greece?", answer: "Athens" },
      { question: "What is the capital of Afghanistan?", answer: "Kabul" },
      { question: "What is the primary ingredient in a traditional falafel?", answer: "Chickpeas" },
      { question: "What is the capital of Bangladesh?", answer: "Dhaka" },
      { question: "What is the largest lake in the world?", answer: "Caspian Sea" },
      { question: "What is the capital of Sri Lanka?", answer: "Sri Jayawardenepura Kotte" },
      { question: "What is the main ingredient in a traditional borscht?", answer: "Beetroot" },
      { question: "What is the capital of Nepal?", answer: "Kathmandu" },
      { question: "What is the most famous mountain range in the world?", answer: "Himalayas" },
      { question: "What is the capital of Uzbekistan?", answer: "Tashkent" },
      { question: "What is the primary ingredient in a traditional chowder?", answer: "Clams" },
      { question: "What is the capital of Kazakhstan?", answer: "Nur-Sultan" },
      { question: "What is the largest rainforest in the world?", answer: "Amazon Rainforest" },
      { question: "What is the capital of Belarus?", answer: "Minsk" },
      { question: "What is the main ingredient in a traditional paella?", answer: "Rice" },
      { question: "What is the capital of Armenia?", answer: "Yerevan" },
      { question: "What is the most famous ancient wonder of the world?", answer: "Great Pyramid of Giza" },
      { question: "What is the capital of Georgia?", answer: "Tbilisi" },
      { question: "What is the primary ingredient in a traditional moussaka?", answer: "Eggplant" },
      { question: "What is the capital of Azerbaijan?", answer: "Baku" },
      { question: "What is the largest city in the Middle East?", answer: "Istanbul" },
      { question: "What is the capital of Qatar?", answer: "Doha" },
      { question: "What is the main ingredient in a traditional goulash?", answer: "Meat" },
      { question: "What is the capital of Bahrain?", answer: "Manama" },
      { question: "What is the most famous festival in India?", answer: "Diwali" },
      { question: "What is the capital of Oman?", answer: "Muscat" },
      { question: "What is the primary ingredient in a traditional baklava?", answer: "Phyllo dough" },
      { question: "What is the capital of Kuwait?", answer: "Kuwait City" },
      { question: "What is the largest city in the Caribbean?", answer: "Havana" },
      { question: "What is the capital of Jamaica?", answer: "Kingston" },
      { question: "What is the main ingredient in a traditional jerk chicken?", answer: "Chicken" },
      { question: "What is the capital of the Dominican Republic?", answer: "Santo Domingo" },
      { question: "What is the most famous beach in the world?", answer: "Copacabana" },
      { question: "What is the capital of Cuba?", answer: "Havana" },
      { question: "What is the primary ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Puerto Rico?", answer: "San Juan" },
      { question: "What is the largest city in South America?", answer: "São Paulo" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Cornmeal" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the most famous landmark in Brazil?", answer: "Christ the Redeemer" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the primary ingredient in a traditional empanada?", answer: "Dough" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Africa?", answer: "Lagos" },
      { question: "What is the capital of Egypt?", answer: "Cairo" },
      { question: "What is the main ingredient in a traditional tagine?", answer: "Meat" },
      { question: "What is the capital of Libya?", answer: "Tripoli" },
      { question: "What is the most famous ancient city in the Middle East?", answer: "Petra" },
      { question: "What is the capital of Syria?", answer: "Damascus" },
      { question: "What is the primary ingredient in a traditional shawarma?", answer: "Meat" },
      { question: "What is the capital of Lebanon?", answer: "Beirut" },
      { question: "What is the largest city in the Caucasus region?", answer: "Baku" },
      { question: "What is the capital of Armenia?", answer: "Yerevan" },
      { question: "What is the main ingredient in a traditional khachapuri?", answer: "Cheese" },
      { question: "What is the capital of Georgia?", answer: "Tbilisi" },
      { question: "What is the most famous ancient city in Central Asia?", answer: "Samarkand" },
      { question: "What is the capital of Uzbekistan?", answer: "Tashkent" },
      { question: "What is the primary ingredient in a traditional plov?", answer: "Rice" },
      { question: "What is the capital of Kazakhstan?", answer: "Nur-Sultan" },
      { question: "What is the largest city in Central Asia?", answer: "Almaty" },
      { question: "What is the capital of Kyrgyzstan?", answer: "Bishkek" },
      { question: "What is the main ingredient in a traditional laghman?", answer: "Noodles" },
      { question: "What is the capital of Tajikistan?", answer: "Dushanbe" },
      { question: "What is the most famous mountain in Central Asia?", answer: "Pamir" },
      { question: "What is the capital of Turkmenistan?", answer: "Ashgabat" },
      { question: "What is the primary ingredient in a traditional manty?", answer: "Dough" },
      { question: "What is the capital of Mongolia?", answer: "Ulaanbaatar" },
      { question: "What is the largest city in Mongolia?", answer: "Ulaanbaatar" },
      { question: "What is the main ingredient in a traditional buuz?", answer: "Meat" },
      { question: "What is the capital of Bhutan?", answer: "Thimphu" },
      { question: "What is the most famous festival in Bhutan?", answer: "Tshechu" },
      { question: "What is the capital of Nepal?", answer: "Kathmandu" },
      { question: "What is the primary ingredient in a traditional momo?", answer: "Meat" },
      { question: "What is the capital of Sri Lanka?", answer: "Sri Jayawardenepura Kotte" },
      { question: "What is the largest city in Sri Lanka?", answer: "Colombo" },
      { question: "What is the main ingredient in a traditional kottu?", answer: "Roti" },
      { question: "What is the capital of Maldives?", answer: "Malé" },
      { question: "What is the most famous beach in the Maldives?", answer: "Maafushi" },
      { question: "What is the capital of Afghanistan?", answer: "Kabul" },
      { question: "What is the primary ingredient in a traditional kebab?", answer: "Meat" },
      { question: "What is the capital of Pakistan?", answer: "Islamabad" },
      { question: "What is the largest city in Pakistan?", answer: "Karachi" },
      { question: "What is the main ingredient in a traditional biryani?", answer: "Rice" },
      { question: "What is the capital of India?", answer: "New Delhi" },
      { question: "What is the most famous festival in India?", answer: "Diwali" },
      { question: "What is the capital of Bangladesh?", answer: "Dhaka" },
      { question: "What is the primary ingredient in a traditional pitha?", answer: "Rice" },
      { question: "What is the capital of Myanmar?", answer: "Naypyidaw" },
      { question: "What is the largest city in Myanmar?", answer: "Yangon" },
      { question: "What is the main ingredient in a traditional mohinga?", answer: "Fish" },
      { question: "What is the capital of Thailand?", answer: "Bangkok" },
      { question: "What is the most famous festival in Thailand?", answer: "Songkran" },
      { question: "What is the capital of Laos?", answer: "Vientiane" },
      { question: "What is the primary ingredient in a traditional larb?", answer: "Meat" },
      { question: "What is the capital of Cambodia?", answer: "Phnom Penh" },
      { question: "What is the largest city in Cambodia?", answer: "Phnom Penh" },
      { question: "What is the main ingredient in a traditional amok?", answer: "Fish" },
      { question: "What is the capital of Vietnam?", answer: "Hanoi" },
      { question: "What is the most famous festival in Vietnam?", answer: "Tet" },
      { question: "What is the capital of Malaysia?", answer: "Kuala Lumpur" },
      { question: "What is the largest city in Malaysia?", answer: "Kuala Lumpur" },
      { question: "What is the main ingredient in a traditional nasi lemak?", answer: "Rice" },
      { question: "What is the capital of Singapore?", answer: "Singapore" },
      { question: "What is the most famous landmark in Singapore?", answer: "Marina Bay Sands" },
      { question: "What is the capital of Brunei?", answer: "Bandar Seri Begawan" },
      { question: "What is the largest city in Brunei?", answer: "Bandar Seri Begawan" },
      { question: "What is the main ingredient in a traditional ambuyat?", answer: "Sago" },
      { question: "What is the capital of the Philippines?", answer: "Manila" },
      { question: "What is the largest city in the Philippines?", answer: "Quezon City" },
      { question: "What is the main ingredient in a traditional adobo?", answer: "Meat" },
      { question: "What is the capital of Indonesia?", answer: "Jakarta" },
      { question: "What is the largest city in Indonesia?", answer: "Jakarta" },
      { question: "What is the main ingredient in a traditional rendang?", answer: "Beef" },
      { question: "What is the capital of East Timor?", answer: "Dili" },
      { question: "What is the largest city in East Timor?", answer: "Dili" },
      { question: "What is the main ingredient in a traditional ikan bakar?", answer: "Fish" },
      { question: "What is the capital of Papua New Guinea?", answer: "Port Moresby" },
      { question: "What is the largest city in Papua New Guinea?", answer: "Port Moresby" },
      { question: "What is the main ingredient in a traditional mumu?", answer: "Pork" },
      { question: "What is the capital of the Solomon Islands?", answer: "Honiara" },
      { question: "What is the largest city in the Solomon Islands?", answer: "Honiara" },
      { question: "What is the main ingredient in a traditional kokoda?", answer: "Fish" },
      { question: "What is the capital of Vanuatu?", answer: "Port Vila" },
      { question: "What is the largest city in Vanuatu?", answer: "Port Vila" },
      { question: "What is the main ingredient in a traditional laplap?", answer: "Taro" },
      { question: "What is the capital of Fiji?", answer: "Suva" },
      { question: "What is the largest city in Fiji?", answer: "Suva" },
      { question: "What is the main ingredient in a traditional kokoda?", answer: "Fish" },
      { question: "What is the capital of Samoa?", answer: "Apia" },
      { question: "What is the largest city in Samoa?", answer: "Apia" },
      { question: "What is the main ingredient in a traditional palusami?", answer: "Taro leaves" },
      { question: "What is the capital of Tonga?", answer: "Nuku'alofa" },
      { question: "What is the largest city in Tonga?", answer: "Nuku'alofa" },
      { question: "What is the main ingredient in a traditional lu?", answer: "Taro leaves" },
      { question: "What is the capital of Tuvalu?", answer: "Funafuti" },
      { question: "What is the largest city in Tuvalu?", answer: "Funafuti" },
      { question: "What is the main ingredient in a traditional pulaka?", answer: "Taro" },
      { question: "What is the capital of Kiribati?", answer: "Tarawa" },
      { question: "What is the largest city in Kiribati?", answer: "Tarawa" },
      { question: "What is the main ingredient in a traditional te-bua?", answer: "Fish" },
      { question: "What is the capital of Micronesia?", answer: "Palikir" },
      { question: "What is the largest city in Micronesia?", answer: "Weno" },
      { question: "What is the main ingredient in a traditional tinola?", answer: "Chicken" },
      { question: "What is the capital of the Marshall Islands?", answer: "Majuro" },
      { question: "What is the largest city in the Marshall Islands?", answer: "Majuro" },
      { question: "What is the main ingredient in a traditional breadfruit?", answer: "Breadfruit" },
      { question: "What is the capital of Palau?", answer: "Ngerulmud" },
      { question: "What is the largest city in Palau?", answer: "Koror" },
      { question: "What is the main ingredient in a traditional tinola?", answer: "Chicken" },
      { question: "What is the capital of Nauru?", answer: "Yaren" },
      { question: "What is the largest city in Nauru?", answer: "Yaren" },
      { question: "What is the main ingredient in a traditional coconut fish?", answer: "Fish" },
      { question: "What is the capital of the United States?", answer: "Washington, D.C." },
      { question: "What is the largest city in the United States?", answer: "New York City" },
      { question: "What is the main ingredient in a traditional hamburger?", answer: "Beef" },
      { question: "What is the capital of Canada?", answer: "Ottawa" },
      { question: "What is the largest city in Canada?", answer: "Toronto" },
      { question: "What is the main ingredient in a traditional poutine?", answer: "Fries" },
      { question: "What is the capital of Mexico?", answer: "Mexico City" },
      { question: "What is the largest city in Mexico?", answer: "Mexico City" },
      { question: "What is the main ingredient in a traditional mole?", answer: "Chili" },
      { question: "What is the capital of Guatemala?", answer: "Guatemala City" },
      { question: "What is the largest city in Guatemala?", answer: "Guatemala City" },
      { question: "What is the main ingredient in a traditional pepian?", answer: "Meat" },
      { question: "What is the capital of Honduras?", answer: "Tegucigalpa" },
      { question: "What is the largest city in Honduras?", answer: "Tegucigalpa" },
      { question: "What is the main ingredient in a traditional baleada?", answer: "Tortilla" },
      { question: "What is the capital of El Salvador?", answer: "San Salvador" },
      { question: "What is the largest city in El Salvador?", answer: "San Salvador" },
      { question: "What is the main ingredient in a traditional pupusa?", answer: "Corn" },
      { question: "What is the capital of Nicaragua?", answer: "Managua" },
      { question: "What is the largest city in Nicaragua?", answer: "Managua" },
      { question: "What is the main ingredient in a traditional vigorón?", answer: "Pork" },
      { question: "What is the capital of Costa Rica?", answer: "San José" },
      { question: "What is the largest city in Costa Rica?", answer: "San José" },
      { question: "What is the main ingredient in a traditional gallo pinto?", answer: "Rice" },
      { question: "What is the capital of Panama?", answer: "Panama City" },
      { question: "What is the largest city in Panama?", answer: "Panama City" },
      { question: "What is the main ingredient in a traditional sancocho?", answer: "Chicken" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the largest city in Colombia?", answer: "Bogotá" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Corn" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the largest city in Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional hallaca?", answer: "Meat" },
      { question: "What is the capital of Ecuador?", answer: "Quito" },
      { question: "What is the largest city in Ecuador?", answer: "Guayaquil" },
      { question: "What is the main ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the largest city in Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional lomo saltado?", answer: "Beef" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the largest city in Bolivia?", answer: "Santa Cruz" },
      { question: "What is the main ingredient in a traditional salteña?", answer: "Meat" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the largest city in Paraguay?", answer: "Asunción" },
      { question: "What is the main ingredient in a traditional sopa paraguaya?", answer: "Corn" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Chile?", answer: "Santiago" },
      { question: "What is the main ingredient in a traditional pastel de choclo?", answer: "Corn" },
      { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
      { question: "What is the largest city in Argentina?", answer: "Buenos Aires" },
      { question: "What is the main ingredient in a traditional empanada?", answer: "Dough" },
      { question: "What is the capital of Uruguay?", answer: "Montevideo" },
      { question: "What is the largest city in Uruguay?", answer: "Montevideo" },
      { question: "What is the main ingredient in a traditional chivito?", answer: "Beef" },
      { question: "What is the capital of Brazil?", answer: "Brasília" },
      { question: "What is the largest city in Brazil?", answer: "São Paulo" },
      { question: "What is the main ingredient in a traditional feijoada?", answer: "Beans" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Chile?", answer: "Santiago" },
      { question: "What is the main ingredient in a traditional pisco sour?", answer: "Pisco" },
      { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
      { question: "What is the largest city in Argentina?", answer: "Buenos Aires" },
      { question: "What is the main ingredient in a traditional dulce de leche?", answer: "Milk" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the largest city in Paraguay?", answer: "Asunción" },
      { question: "What is the main ingredient in a traditional chipa?", answer: "Cheese" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the largest city in Bolivia?", answer: "Santa Cruz" },
      { question: "What is the main ingredient in a traditional salteña?", answer: "Meat" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the largest city in Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional lomo saltado?", answer: "Beef" },
      { question: "What is the capital of Ecuador?", answer: "Quito" },
      { question: "What is the largest city in Ecuador?", answer: "Guayaquil" },
      { question: "What is the main ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the largest city in Colombia?", answer: "Bogotá" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Corn" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the largest city in Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional hallaca?", answer: "Meat" },
      { question: "What is the capital of Mexico?", answer: "Mexico City" },
      { question: "What is the largest city in Mexico?", answer: "Mexico City" },
      { question: "What is the main ingredient in a traditional mole?", answer: "Chili" },
      { question: "What is the capital of Guatemala?", answer: "Guatemala City" },
      { question: "What is the largest city in Guatemala?", answer: "Guatemala City" },
      { question: "What is the main ingredient in a traditional pepian?", answer: "Meat" },
      { question: "What is the capital of Honduras?", answer: "Tegucigalpa" },
      { question: "What is the largest city in Honduras?", answer: "Tegucigalpa" },
      { question: "What is the main ingredient in a traditional baleada?", answer: "Tortilla" },
      { question: "What is the capital of El Salvador?", answer: "San Salvador" },
      { question: "What is the largest city in El Salvador?", answer: "San Salvador" },
      { question: "What is the main ingredient in a traditional pupusa?", answer: "Corn" },
      { question: "What is the capital of Nicaragua?", answer: "Managua" },
      { question: "What is the largest city in Nicaragua?", answer: "Managua" },
      { question: "What is the main ingredient in a traditional vigorón?", answer: "Pork" },
      { question: "What is the capital of Costa Rica?", answer: "San José" },
      { question: "What is the largest city in Costa Rica?", answer: "San José" },
      { question: "What is the main ingredient in a traditional gallo pinto?", answer: "Rice" },
      { question: "What is the capital of Panama?", answer: "Panama City" },
      { question: "What is the largest city in Panama?", answer: "Panama City" },
      { question: "What is the main ingredient in a traditional sancocho?", answer: "Chicken" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the largest city in Colombia?", answer: "Bogotá" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Corn" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the largest city in Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional hallaca?", answer: "Meat" },
      { question: "What is the capital of Ecuador?", answer: "Quito" },
      { question: "What is the largest city in Ecuador?", answer: "Guayaquil" },
      { question: "What is the main ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the largest city in Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional lomo saltado?", answer: "Beef" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the largest city in Bolivia?", answer: "Santa Cruz" },
      { question: "What is the main ingredient in a traditional salteña?", answer: "Meat" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the largest city in Paraguay?", answer: "Asunción" },
      { question: "What is the main ingredient in a traditional sopa paraguaya?", answer: "Corn" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Chile?", answer: "Santiago" },
      { question: "What is the main ingredient in a traditional pastel de choclo?", answer: "Corn" },
      { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
      { question: "What is the largest city in Argentina?", answer: "Buenos Aires" },
      { question: "What is the main ingredient in a traditional empanada?", answer: "Dough" },
      { question: "What is the capital of Uruguay?", answer: "Montevideo" },
      { question: "What is the largest city in Uruguay?", answer: "Montevideo" },
      { question: "What is the main ingredient in a traditional chivito?", answer: "Beef" },
      { question: "What is the capital of Brazil?", answer: "Brasília" },
      { question: "What is the largest city in Brazil?", answer: "São Paulo" },
      { question: "What is the main ingredient in a traditional feijoada?", answer: "Beans" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Chile?", answer: "Santiago" },
      { question: "What is the main ingredient in a traditional pisco sour?", answer: "Pisco" },
      { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
      { question: "What is the largest city in Argentina?", answer: "Buenos Aires" },
      { question: "What is the main ingredient in a traditional dulce de leche?", answer: "Milk" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the largest city in Paraguay?", answer: "Asunción" },
      { question: "What is the main ingredient in a traditional chipa?", answer: "Cheese" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the largest city in Bolivia?", answer: "Santa Cruz" },
      { question: "What is the main ingredient in a traditional salteña?", answer: "Meat" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the largest city in Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional lomo saltado?", answer: "Beef" },
      { question: "What is the capital of Ecuador?", answer: "Quito" },
      { question: "What is the largest city in Ecuador?", answer: "Guayaquil" },
      { question: "What is the main ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the largest city in Colombia?", answer: "Bogotá" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Corn" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the largest city in Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional hallaca?", answer: "Meat" },
      { question: "What is the capital of Mexico?", answer: "Mexico City" },
      { question: "What is the largest city in Mexico?", answer: "Mexico City" },
      { question: "What is the main ingredient in a traditional mole?", answer: "Chili" },
      { question: "What is the capital of Guatemala?", answer: "Guatemala City" },
      { question: "What is the largest city in Guatemala?", answer: "Guatemala City" },
      { question: "What is the main ingredient in a traditional pepian?", answer: "Meat" },
      { question: "What is the capital of Honduras?", answer: "Tegucigalpa" },
      { question: "What is the largest city in Honduras?", answer: "Tegucigalpa" },
      { question: "What is the main ingredient in a traditional baleada?", answer: "Tortilla" },
      { question: "What is the capital of El Salvador?", answer: "San Salvador" },
      { question: "What is the largest city in El Salvador?", answer: "San Salvador" },
      { question: "What is the main ingredient in a traditional pupusa?", answer: "Corn" },
      { question: "What is the capital of Nicaragua?", answer: "Managua" },
      { question: "What is the largest city in Nicaragua?", answer: "Managua" },
      { question: "What is the main ingredient in a traditional vigorón?", answer: "Pork" },
      { question: "What is the capital of Costa Rica?", answer: "San José" },
      { question: "What is the largest city in Costa Rica?", answer: "San José" },
      { question: "What is the main ingredient in a traditional gallo pinto?", answer: "Rice" },
      { question: "What is the capital of Panama?", answer: "Panama City" },
      { question: "What is the largest city in Panama?", answer: "Panama City" },
      { question: "What is the main ingredient in a traditional sancocho?", answer: "Chicken" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the largest city in Colombia?", answer: "Bogotá" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Corn" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the largest city in Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional hallaca?", answer: "Meat" },
      { question: "What is the capital of Ecuador?", answer: "Quito" },
      { question: "What is the largest city in Ecuador?", answer: "Guayaquil" },
      { question: "What is the main ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the largest city in Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional lomo saltado?", answer: "Beef" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the largest city in Bolivia?", answer: "Santa Cruz" },
      { question: "What is the main ingredient in a traditional salteña?", answer: "Meat" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the largest city in Paraguay?", answer: "Asunción" },
      { question: "What is the main ingredient in a traditional sopa paraguaya?", answer: "Corn" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Chile?", answer: "Santiago" },
      { question: "What is the main ingredient in a traditional pastel de choclo?", answer: "Corn" },
      { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
      { question: "What is the largest city in Argentina?", answer: "Buenos Aires" },
      { question: "What is the main ingredient in a traditional empanada?", answer: "Dough" },
      { question: "What is the capital of Uruguay?", answer: "Montevideo" },
      { question: "What is the largest city in Uruguay?", answer: "Montevideo" },
      { question: "What is the main ingredient in a traditional chivito?", answer: "Beef" },
      { question: "What is the capital of Brazil?", answer: "Brasília" },
      { question: "What is the largest city in Brazil?", answer: "São Paulo" },
      { question: "What is the main ingredient in a traditional feijoada?", answer: "Beans" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Chile?", answer: "Santiago" },
      { question: "What is the main ingredient in a traditional pisco sour?", answer: "Pisco" },
      { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
      { question: "What is the largest city in Argentina?", answer: "Buenos Aires" },
      { question: "What is the main ingredient in a traditional dulce de leche?", answer: "Milk" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the largest city in Paraguay?", answer: "Asunción" },
      { question: "What is the main ingredient in a traditional chipa?", answer: "Cheese" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the largest city in Bolivia?", answer: "Santa Cruz" },
      { question: "What is the main ingredient in a traditional salteña?", answer: "Meat" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the largest city in Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional lomo saltado?", answer: "Beef" },
      { question: "What is the capital of Ecuador?", answer: "Quito" },
      { question: "What is the largest city in Ecuador?", answer: "Guayaquil" },
      { question: "What is the main ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the largest city in Colombia?", answer: "Bogotá" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Corn" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the largest city in Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional hallaca?", answer: "Meat" },
      { question: "What is the capital of Mexico?", answer: "Mexico City" },
      { question: "What is the largest city in Mexico?", answer: "Mexico City" },
      { question: "What is the main ingredient in a traditional mole?", answer: "Chili" },
      { question: "What is the capital of Guatemala?", answer: "Guatemala City" },
      { question: "What is the largest city in Guatemala?", answer: "Guatemala City" },
      { question: "What is the main ingredient in a traditional pepian?", answer: "Meat" },
      { question: "What is the capital of Honduras?", answer: "Tegucigalpa" },
      { question: "What is the largest city in Honduras?", answer: "Tegucigalpa" },
      { question: "What is the main ingredient in a traditional baleada?", answer: "Tortilla" },
      { question: "What is the capital of El Salvador?", answer: "San Salvador" },
      { question: "What is the largest city in El Salvador?", answer: "San Salvador" },
      { question: "What is the main ingredient in a traditional pupusa?", answer: "Corn" },
      { question: "What is the capital of Nicaragua?", answer: "Managua" },
      { question: "What is the largest city in Nicaragua?", answer: "Managua" },
      { question: "What is the main ingredient in a traditional vigorón?", answer: "Pork" },
      { question: "What is the capital of Costa Rica?", answer: "San José" },
      { question: "What is the largest city in Costa Rica?", answer: "San José" },
      { question: "What is the main ingredient in a traditional gallo pinto?", answer: "Rice" },
      { question: "What is the capital of Panama?", answer: "Panama City" },
      { question: "What is the largest city in Panama?", answer: "Panama City" },
      { question: "What is the main ingredient in a traditional sancocho?", answer: "Chicken" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the largest city in Colombia?", answer: "Bogotá" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Corn" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the largest city in Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional hallaca?", answer: "Meat" },
      { question: "What is the capital of Ecuador?", answer: "Quito" },
      { question: "What is the largest city in Ecuador?", answer: "Guayaquil" },
      { question: "What is the main ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the largest city in Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional lomo saltado?", answer: "Beef" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the largest city in Bolivia?", answer: "Santa Cruz" },
      { question: "What is the main ingredient in a traditional salteña?", answer: "Meat" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the largest city in Paraguay?", answer: "Asunción" },
      { question: "What is the main ingredient in a traditional sopa paraguaya?", answer: "Corn" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Chile?", answer: "Santiago" },
      { question: "What is the main ingredient in a traditional pastel de choclo?", answer: "Corn" },
      { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
      { question: "What is the largest city in Argentina?", answer: "Buenos Aires" },
      { question: "What is the main ingredient in a traditional empanada?", answer: "Dough" },
      { question: "What is the capital of Uruguay?", answer: "Montevideo" },
      { question: "What is the largest city in Uruguay?", answer: "Montevideo" },
      { question: "What is the main ingredient in a traditional chivito?", answer: "Beef" },
      { question: "What is the capital of Brazil?", answer: "Brasília" },
      { question: "What is the largest city in Brazil?", answer: "São Paulo" },
      { question: "What is the main ingredient in a traditional feijoada?", answer: "Beans" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Chile?", answer: "Santiago" },
      { question: "What is the main ingredient in a traditional pisco sour?", answer: "Pisco" },
      { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
      { question: "What is the largest city in Argentina?", answer: "Buenos Aires" },
      { question: "What is the main ingredient in a traditional dulce de leche?", answer: "Milk" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the largest city in Paraguay?", answer: "Asunción" },
      { question: "What is the main ingredient in a traditional chipa?", answer: "Cheese" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the largest city in Bolivia?", answer: "Santa Cruz" },
      { question: "What is the main ingredient in a traditional salteña?", answer: "Meat" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the largest city in Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional lomo saltado?", answer: "Beef" },
      { question: "What is the capital of Ecuador?", answer: "Quito" },
      { question: "What is the largest city in Ecuador?", answer: "Guayaquil" },
      { question: "What is the main ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the largest city in Colombia?", answer: "Bogotá" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Corn" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the largest city in Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional hallaca?", answer: "Meat" },
      { question: "What is the capital of Mexico?", answer: "Mexico City" },
      { question: "What is the largest city in Mexico?", answer: "Mexico City" },
      { question: "What is the main ingredient in a traditional mole?", answer: "Chili" },
      { question: "What is the capital of Guatemala?", answer: "Guatemala City" },
      { question: "What is the largest city in Guatemala?", answer: "Guatemala City" },
      { question: "What is the main ingredient in a traditional pepian?", answer: "Meat" },
      { question: "What is the capital of Honduras?", answer: "Tegucigalpa" },
      { question: "What is the largest city in Honduras?", answer: "Tegucigalpa" },
      { question: "What is the main ingredient in a traditional baleada?", answer: "Tortilla" },
      { question: "What is the capital of El Salvador?", answer: "San Salvador" },
      { question: "What is the largest city in El Salvador?", answer: "San Salvador" },
      { question: "What is the main ingredient in a traditional pupusa?", answer: "Corn" },
      { question: "What is the capital of Nicaragua?", answer: "Managua" },
      { question: "What is the largest city in Nicaragua?", answer: "Managua" },
      { question: "What is the main ingredient in a traditional vigorón?", answer: "Pork" },
      { question: "What is the capital of Costa Rica?", answer: "San José" },
      { question: "What is the largest city in Costa Rica?", answer: "San José" },
      { question: "What is the main ingredient in a traditional gallo pinto?", answer: "Rice" },
      { question: "What is the capital of Panama?", answer: "Panama City" },
      { question: "What is the largest city in Panama?", answer: "Panama City" },
      { question: "What is the main ingredient in a traditional sancocho?", answer: "Chicken" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the largest city in Colombia?", answer: "Bogotá" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Corn" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the largest city in Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional hallaca?", answer: "Meat" },
      { question: "What is the capital of Ecuador?", answer: "Quito" },
      { question: "What is the largest city in Ecuador?", answer: "Guayaquil" },
      { question: "What is the main ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the largest city in Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional lomo saltado?", answer: "Beef" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the largest city in Bolivia?", answer: "Santa Cruz" },
      { question: "What is the main ingredient in a traditional salteña?", answer: "Meat" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the largest city in Paraguay?", answer: "Asunción" },
      { question: "What is the main ingredient in a traditional sopa paraguaya?", answer: "Corn" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Chile?", answer: "Santiago" },
      { question: "What is the main ingredient in a traditional pastel de choclo?", answer: "Corn" },
      { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
      { question: "What is the largest city in Argentina?", answer: "Buenos Aires" },
      { question: "What is the main ingredient in a traditional empanada?", answer: "Dough" },
      { question: "What is the capital of Uruguay?", answer: "Montevideo" },
      { question: "What is the largest city in Uruguay?", answer: "Montevideo" },
      { question: "What is the main ingredient in a traditional chivito?", answer: "Beef" },
      { question: "What is the capital of Brazil?", answer: "Brasília" },
      { question: "What is the largest city in Brazil?", answer: "São Paulo" },
      { question: "What is the main ingredient in a traditional feijoada?", answer: "Beans" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Chile?", answer: "Santiago" },
      { question: "What is the main ingredient in a traditional pisco sour?", answer: "Pisco" },
      { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
      { question: "What is the largest city in Argentina?", answer: "Buenos Aires" },
      { question: "What is the main ingredient in a traditional dulce de leche?", answer: "Milk" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the largest city in Paraguay?", answer: "Asunción" },
      { question: "What is the main ingredient in a traditional chipa?", answer: "Cheese" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the largest city in Bolivia?", answer: "Santa Cruz" },
      { question: "What is the main ingredient in a traditional salteña?", answer: "Meat" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the largest city in Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional lomo saltado?", answer: "Beef" },
      { question: "What is the capital of Ecuador?", answer: "Quito" },
      { question: "What is the largest city in Ecuador?", answer: "Guayaquil" },
      { question: "What is the main ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the largest city in Colombia?", answer: "Bogotá" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Corn" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the largest city in Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional hallaca?", answer: "Meat" },
      { question: "What is the capital of Mexico?", answer: "Mexico City" },
      { question: "What is the largest city in Mexico?", answer: "Mexico City" },
      { question: "What is the main ingredient in a traditional mole?", answer: "Chili" },
      { question: "What is the capital of Guatemala?", answer: "Guatemala City" },
      { question: "What is the largest city in Guatemala?", answer: "Guatemala City" },
      { question: "What is the main ingredient in a traditional pepian?", answer: "Meat" },
      { question: "What is the capital of Honduras?", answer: "Tegucigalpa" },
      { question: "What is the largest city in Honduras?", answer: "Tegucigalpa" },
      { question: "What is the main ingredient in a traditional baleada?", answer: "Tortilla" },
      { question: "What is the capital of El Salvador?", answer: "San Salvador" },
      { question: "What is the largest city in El Salvador?", answer: "San Salvador" },
      { question: "What is the main ingredient in a traditional pupusa?", answer: "Corn" },
      { question: "What is the capital of Nicaragua?", answer: "Managua" },
      { question: "What is the largest city in Nicaragua?", answer: "Managua" },
      { question: "What is the main ingredient in a traditional vigorón?", answer: "Pork" },
      { question: "What is the capital of Costa Rica?", answer: "San José" },
      { question: "What is the largest city in Costa Rica?", answer: "San José" },
      { question: "What is the main ingredient in a traditional gallo pinto?", answer: "Rice" },
      { question: "What is the capital of Panama?", answer: "Panama City" },
      { question: "What is the largest city in Panama?", answer: "Panama City" },
      { question: "What is the main ingredient in a traditional sancocho?", answer: "Chicken" },
      { question: "What is the capital of Colombia?", answer: "Bogotá" },
      { question: "What is the largest city in Colombia?", answer: "Bogotá" },
      { question: "What is the main ingredient in a traditional arepa?", answer: "Corn" },
      { question: "What is the capital of Venezuela?", answer: "Caracas" },
      { question: "What is the largest city in Venezuela?", answer: "Caracas" },
      { question: "What is the main ingredient in a traditional hallaca?", answer: "Meat" },
      { question: "What is the capital of Ecuador?", answer: "Quito" },
      { question: "What is the largest city in Ecuador?", answer: "Guayaquil" },
      { question: "What is the main ingredient in a traditional ceviche?", answer: "Fish" },
      { question: "What is the capital of Peru?", answer: "Lima" },
      { question: "What is the largest city in Peru?", answer: "Lima" },
      { question: "What is the main ingredient in a traditional lomo saltado?", answer: "Beef" },
      { question: "What is the capital of Bolivia?", answer: "Sucre" },
      { question: "What is the largest city in Bolivia?", answer: "Santa Cruz" },
      { question: "What is the main ingredient in a traditional salteña?", answer: "Meat" },
      { question: "What is the capital of Paraguay?", answer: "Asunción" },
      { question: "What is the largest city in Paraguay?", answer: "Asunción" },
      { question: "What is the main ingredient in a traditional sopa paraguaya?", answer: "Corn" },
      { question: "What is the capital of Chile?", answer: "Santiago" },
      { question: "What is the largest city in Chile?", answer: "Santiago" },
      { question: "What is the main ingredient in a traditional pastel de choclo?", answer: "Corn" },
      { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
      { question: "What is the largest city in Argentina?", answer: "Buenos Aires" },
      { question: "What is the main ingredient in a traditional empanada?", answer: "Dough" },
      { question: "What is the capital of Uruguay?", answer: "Montevideo" },
  ];
  
  const randomQuestion = questions[Math.floor(Math.random() * questions.length)];
  const userAnswer = prompt(randomQuestion.question);
  
  if (userAnswer.toLowerCase() === randomQuestion.answer.toLowerCase()) {
      appendMessage(BOT_NAME, BOT_IMG, "left", "Correct! 🎉");
  } else {
      appendMessage(BOT_NAME, BOT_IMG, "left", `Wrong! The correct answer is ${randomQuestion.answer}.`);
  }
}



function guessTheCountry() {
  const countries = ["France", "Germany", "Italy", "Spain", "Japan"];
  const randomCountry = countries[Math.floor(Math.random() * countries.length)];
  
  const userGuess = prompt("Guess the country:");
  
  if (userGuess.toLowerCase() === randomCountry.toLowerCase()) {
      appendMessage(BOT_NAME, BOT_IMG, "left", "Correct! 🎉 The country is " + randomCountry + ".");
  } else {
      appendMessage(BOT_NAME, BOT_IMG, "left", "Wrong! The correct country was " + randomCountry + ".");
  }
}

function nameACountry() {
  const countries = [
    { name: "France", hint: "Known for the Eiffel Tower and delicious pastries!" },
    { name: "Germany", hint: "Famous for its beer and Oktoberfest!" },
    { name: "Italy", hint: "Home of pizza and the Colosseum!" },
    { name: "Spain", hint: "Renowned for flamenco dancing and paella!" },
    { name: "Japan", hint: "Famous for sushi and cherry blossoms!" }
  ];
  
  const randomCountry = countries[Math.floor(Math.random() * countries.length)];
  
  // Provide the hint first
  appendMessage(BOT_NAME, BOT_IMG, "left", "Here's a hint: " + randomCountry.hint);
  
  // Ask the user to guess the country in chat
  appendMessage(BOT_NAME, BOT_IMG, "left", "Can you name the country?");
  
  // Listen for the user's response
  msgerForm.addEventListener("submit", event => {
    event.preventDefault();
    
    const userGuess = msgerInput.value;
    msgerInput.value = ""; // Clear the input field

    // Check the user's guess (case-insensitive)
    if (userGuess && userGuess.toLowerCase() === randomCountry.name.toLowerCase()) {
      appendMessage(BOT_NAME, BOT_IMG, "left", "Correct! 🎉 The country is " + randomCountry.name + ".");
    } else {
      appendMessage(BOT_NAME, BOT_IMG, "left", "Wrong! The correct country was " + randomCountry.name + ".");
    }
  });
}





